### ISSUE TITLE
Error with Java Clients after updating jersey version from 2.25.1 to 2.26

### ISSUE THREAD

**Issue by normansuesstrunk** [weblyzard/weblyzard_api#77]
With Jersey Version 2.26 i get the following error using a Java Client: 

```
java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	...
	at com.weblyzard.api.client.RecognyzeClient.status(RecognyzeClient.java:130)
	at ch.htwchur.jobcockpit.bolt.RecognyzeBoltTestIT.testRecognizeBolt(RecognyzeBoltTestIT.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```
With Jersey Version 2.25.1 the exception does not occur anymore. 
All the Unit Tests work with 2.25.1. 
Would it be possible to downgrade Jersey until a solution is found?

**Comment by AlbertWeichselbraun** [comment]
Done.
